version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
      - npm install
  # pre_build:
  #   commands:
  #     - echo "Running tests"
  #     - npm test
  build:
    commands:
      - echo "Building application"
      - npm run build
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
  base-directory: 'dist' # Change this if your build outputs to a different directory

cache:
  paths:
    - 'node_modules/**/*'
